//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 XrayDCDeburring.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_XRAYDCDEBURRING_FORM        101
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_XrayDCDeburringTYPE         130
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDD_DIALOG_FIRERECORD           173
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDB_BITMAP_MAINTOOLBAR          311
#define IDD_DIALOG_COMMSET              312
#define IDD_DIALOG_TESTPROG             314
#define IDD_DIALOG_PRODUCT              316
#define IDD_DIALOG_PROGITEM             317
#define IDR_MENU_POPUP_PROGRAM          320
#define IDB_BITMAP_FILETREE             321
#define IDD_DIALOG_DETECTINFO_INPUT     352
#define IDD_DIALOG_FIRE_OUTPUT          353
#define IDC_LIST_FIREOUTPUT             1000
#define IDC_STATIC_WORK_STATUS          1002
#define IDC_STATIC_SHIBOQI_STATUS       1003
#define IDC_STATIC_MCU_STATUS           1004
#define IDC_STATIC_BREAKDOWN            1005
#define IDC_STATIC_LOUCURRENT_CH1       1006
#define IDC_STATIC_LOUCURRENT_CH2       1007
#define IDC_COMBO_HIGHTPOWER_COM        1007
#define IDC_STATIC_LOUCURRENT_CH3       1008
#define IDC_COMBO_LOWPOWER_COM          1008
#define IDC_STATIC_LOUCURRENT_CH4       1009
#define IDC_COMBO_MCU_COM               1009
#define IDC_STATIC_JICHAN_CURRENT       1010
#define IDC_EDIT_SHIBOQI                1010
#define IDC_STATIC_JICHUAN_CH           1011
#define IDC_TREE_PRODUCT                1011
#define IDC_COMBO_HIGHTPOWER_BAUDRATE   1011
#define IDC_LIST_INFORMATION            1011
#define IDC_STATIC_BREAKDOWN2           1012
#define IDC_LIST_PROGRAMITEM            1012
#define IDC_STATIC_LOWPOWER_STATUS      1012
#define IDC_COMBO_LOWPOWER_BAUDRATE     1012
#define IDC_STATIC_LOWER_VALTAGE        1013
#define IDC_BUTTON_ADD                  1013
#define IDC_COMBO_MCU_BAUDRATE          1013
#define IDC_STATIC_LOWER_CURRENT        1014
#define IDC_BUTTON_MODIFY               1014
#define IDC_COMBO_SHIBOQI_COM           1014
#define IDC_BUTTON_DELETE               1015
#define IDC_COMBO_SHIBOQI_BAUDRATE      1015
#define IDC_STATIC_HIPOWER_STATUS       1015
#define IDC_EDIT_HIGHTPOWER_LIMIT       1016
#define IDC_STATIC_LOWER_VALTAGE2       1016
#define IDC_STATIC_HIGHT_VALTAGE        1016
#define IDC_EDIT_LOWPOWER               1017
#define IDC_EDIT_PRODUCT                1017
#define IDC_EDIT_STEPS                  1018
#define IDC_EDIT_LOW_POWER              1019
#define IDC_SPIN_STEPS                  1019
#define IDC_EDIT_VALTAGE                1020
#define IDC_EDIT_KEEPTIME               1021
#define IDC_STATIC_CURVE                1021
#define IDC_EDIT_LOW_POWER_CURRENT      1021
#define IDC_STATIC_SPLITLINE            1022
#define IDC_EDIT_LOW_POWERLIMIT         1022
#define IDC_SPIN_REPEATTIMES            1024
#define IDC_SPIN_INCREASE_RATE          1025
#define IDC_BUTTON_START                1026
#define IDC_SPIN_GOBACKSTEPS            1027
#define IDC_BUTTON_CONTINUE             1028
#define IDC_BUTTON_STOP                 1029
#define IDC_STATIC_HIGHTVOLTAGE         1030
#define IDC_STATIC_LOWVOLTAGE           1031
#define IDC_STATIC_FINISHTIMES          1032
#define IDC_STATIC_CURRENTSTEP          1033
#define IDC_STATIC_KEEPTIME_REAL        1034
#define IDC_LIST_PROGITEM               1035
#define IDC_EDIT_TUBE_SN                1036
#define IDC_CHECK_TIME                  1037
#define IDC_SPIN_START_STEP             1037
#define IDC_CHECK_TUBESN                1038
#define IDC_EDIT_TUBESN                 1039
#define IDC_MFCEDITBROWSE_REPORT        1040
#define IDC_BUTTON_REPORT               1041
#define IDC_EDIT_PARTSID                1079
#define IDC_EDIT_REPEATTIMES            1079
#define IDC_COMBO_MACHINENUM            1080
#define IDC_COMBO_PROGSEL               1080
#define IDC_COMBO_WORKSHIFT             1081
#define IDC_COMBO_FACTOR                1081
#define IDC_COMBO_MEASURETYPE           1082
#define IDC_COMBO_INCREASESPEED         1082
#define IDC_EDIT_BATCHNUM               1083
#define IDC_EDIT_PARTSID_SUB            1084
#define IDC_EDIT_INCREASE_RATE          1084
#define IDC_EDIT_GOBACK_STEPS           1086
#define IDC_EDIT_START_STEP             1087
#define IDC_STATIC_DETECT_MODE          1146
#define IDC_STATIC_CURVE_VOLTAGE        1146
#define IDC_EDIT_CURRENTPROG            1151
#define IDC_DATETIMEPICKER_START        1197
#define IDC_DATETIMEPICKER_END          1198
#define IDC_BUTTON_QUERY                1199
#define ID_TOOLBAR_DEVICELINK           32771
#define ID_TOOLBAR_BLACKCORRECT         32772
#define ID_TOOLBAR_WHITECORRECT         32773
#define ID_TOOLBAR_RUNSTOP              32774
#define ID_TOOLBAR_HORANALYZE           32775
#define ID_TOOLBAR_VERANALYZE           32776
#define ID_TOOLBAR_SELECT_AREA          32777
#define ID_TOOLBAR_CAMERAPARAM_SET      32778
#define ID_TOOLBAR_COMMSET              32779
#define ID_TOOLBAR_TESTPLAN             32780
#define ID_TOOLBAR_DEVICE_LINK          32781
#define ID_32782                        32782
#define ID_32783                        32783
#define ID_32784                        32784
#define ID_MENU_CREATEPROGRAM           32785
#define ID_MENU_MODIFYPROGRAM           32786
#define ID_MENU_DELETPROGRAM            32787
#define ID_TOOLBAR_FIRERECORD           32788
#define ID_Menu                         32789
#define ID_32790                        32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_TOOLBAR_SAVEDATA             32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        324
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
